USE liiga;
DROP TABLE IF EXISTS `Joukkueet` CASCADE;
DROP TABLE IF EXISTS `Pelaajat` CASCADE;
DROP TABLE IF EXISTS `Ottelut` CASCADE;
DROP TABLE IF EXISTS `Laukaisut` CASCADE;
DROP TABLE IF EXISTS `PelaajanJoukkueet` CASCADE;
